name: Python Tests and Linting

on:
  pull_request:  # Trigger on pull request
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pylint

      # Step 4: Run PyLint
      - name: Run pylint
        run: |
          pylint app/ tests/ --fail-under=9.0  # Set fail-under to your desired score

      # Step 5: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          pytest --cov=app --cov-fail-under=100  # Ensure 100% coverage

      # Step 6: Upload coverage report (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
